# Generated by Django 2.2.5 on 2019-12-16 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publishied_date',
        ),
        migrations.AddField(
            model_name='post',
            name='publishid_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 16, 46, 55, 380089, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 16, 16, 46, 55, 380066, tzinfo=utc)),
        ),
    ]
