# Generated by Django 2.2.5 on 2019-12-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191223_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publishid_date',
            field=models.DateTimeField(default=None),
        ),
    ]
