# Generated by Django 2.2.5 on 2019-12-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191223_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publishid_date',
            new_name='published_date',
        ),
    ]
